service: iguatemi

custom:
  userTableName: user
  userTableArn:
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.userTableName}
  storeTableName: store
  storeTableArn:
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.storeTableName}
  productTableName: product
  productTableArn:
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.productTableName}
provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: sa-east-1
  timeout: 60

iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - SNS:Publish
        - ses:SendEmail
      Resource:
        - ${self:custom.userTableArn}
        - ${self:custom.productTableArn}
        - ${self:custom.storeTableArn}
package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  graphql:
    handler: bin/graphql
    events:
      - http:
          path: /graphql
          method: post
          cors: true

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTableName}
        ProvisionedThroughput:
          ReadCapacityUnits:  3
          WriteCapacityUnits: 3
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    StoreTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.storeTableName}
        ProvisionedThroughput:
          ReadCapacityUnits:  3
          WriteCapacityUnits: 3
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.productTableName}
        ProvisionedThroughput:
          ReadCapacityUnits:  3
          WriteCapacityUnits: 3
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH